# Generated by Django 5.0.4 on 2024-05-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0002_alter_category_options_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
