# Generated by Django 5.0.4 on 2024-05-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0004_service_serviceprovider_booking_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub-categories'},
        ),
    ]
