# Generated by Django 5.0.4 on 2024-05-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0005_alter_subcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular User'), ('provider', 'Service Provider')], default='regular', max_length=20),
        ),
    ]
