# Generated by Django 5.0.4 on 2024-05-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0008_alter_profile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='cities',
            field=models.ManyToManyField(related_name='services', to='iterio_app.city'),
        ),
    ]
