# Generated by Django 5.0.4 on 2024-06-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0010_alter_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='iterio_app.category'),
        ),
        migrations.AddField(
            model_name='service',
            name='cities',
            field=models.ManyToManyField(to='iterio_app.city'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_range',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
