# Generated by Django 5.0.4 on 2024-06-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0011_service_category_service_cities_service_price_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cities',
            field=models.ManyToManyField(related_name='services', to='iterio_app.city'),
        ),
    ]
