# Generated by Django 5.0.4 on 2024-06-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0012_alter_service_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='service_pictures'),
        ),
    ]
