# Generated by Django 5.0.4 on 2024-06-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0013_service_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contact_info',
            field=models.TextField(blank=True),
        ),
    ]
