# Generated by Django 4.2.13 on 2024-06-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0014_service_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='details',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='category',
            name='img_path',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='category',
            name='redirect',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
