# Generated by Django 5.0.4 on 2024-06-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0015_category_details_category_img_path_category_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='availability',
            field=models.TextField(blank=True),
        ),
    ]
