# Generated by Django 5.0.4 on 2024-06-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0016_service_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='availability',
        ),
    ]
