# Generated by Django 5.0.4 on 2024-06-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0018_service_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
    ]
