# Generated by Django 5.0.6 on 2024-06-23 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0020_remove_booking_date_remove_booking_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service_slot',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_service', to='iterio_app.service')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='iterio_app.timeslot'),
        ),
        migrations.DeleteModel(
            name='ServiceSlot',
        ),
    ]
