# Generated by Django 5.0.6 on 2024-07-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0023_chatroom_remove_chatmessage_reciever_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
