# Generated by Django 5.0.6 on 2024-07-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0027_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
