# Generated by Django 5.0.6 on 2024-07-06 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iterio_app', '0029_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Chat Message'},
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
